# Generated by Django 5.0.6 on 2026-06-24 03:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message='wallet_address must be a lowercase 0x-prefixed 40 hex char address.', regex='^0x[a-f0-9]{40}$')])),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('nonce', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('chain_id', models.CharField(default='84532', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
